### ISSUE TITLE
The compiled SASS-file breaks menu

### ISSUE THREAD

**Issue by alexander** [mblode/burger#7]
I installed the menu with Bower. Compiling the SASS-file breaks the menu as seen on the screenshots below.

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/12189439/7632948/71da2020-fa51-11e4-90bb-760b1842cd27.png)

Safari:
![safari](https://cloud.githubusercontent.com/assets/12189439/7632949/71e552ba-fa51-11e4-8104-fe9c99d6bc0f.png)

**Comment by mblode** [comment]
The Sass file must be compiled with autoprefixer to include the vendor prefixes. The minified CSS file includes those prefixes by default.

**Comment by mblode** [comment]
Maybe use Gulp or Grunt?
